{
 "title": "Midgard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Golang", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "go_goroutines{}", "legendFormat": "count" }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "go_gc_duration_seconds{}", "legendFormat": "Quantile {{quantile}}" }
   ]
  },
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{}",
     "legendFormat": "go_memstats_mspan_inuse_bytes"
    },
    { "expr": "go_memstats_mspan_sys_bytes{}", "legendFormat": "go_memstats_mspan_sys_bytes" },
    {
     "expr": "go_memstats_mcache_inuse_bytes{}",
     "legendFormat": "go_memstats_mcache_inuse_bytes"
    },
    { "expr": "go_memstats_mcache_sys_bytes{}", "legendFormat": "go_memstats_mcache_sys_bytes" },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{}",
     "legendFormat": "go_memstats_buck_hash_sys_bytes"
    },
    { "expr": "go_memstats_gc_sys_bytes{}", "legendFormat": "go_memstats_gc_sys_bytes" },
    { "expr": "go_memstats_next_gc_bytes{}", "legendFormat": "go_memstats_next_gc_bytes" }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_heap_alloc_bytes{}", "legendFormat": "go_memstats_heap_alloc_bytes" },
    { "expr": "go_memstats_heap_sys_bytes{}", "legendFormat": "go_memstats_heap_sys_bytes" },
    { "expr": "go_memstats_heap_idle_bytes{}", "legendFormat": "go_memstats_heap_idle_bytes" },
    { "expr": "go_memstats_heap_inuse_bytes{}", "legendFormat": "go_memstats_heap_inuse_bytes" },
    {
     "expr": "go_memstats_heap_released_bytes{}",
     "legendFormat": "go_memstats_heap_released_bytes"
    }
   ]
  },
  { "title": "Midgard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Block Processing Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg(irate(midgard_record_block_process_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.90, avg(irate(midgard_record_block_process_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, avg(irate(midgard_record_block_process_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "50th Percentile"
    }
   ]
  },
  {
   "title": "Event Processing Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg(irate(midgard_record_event_process_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.90, avg(irate(midgard_record_event_process_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, avg(irate(midgard_record_event_process_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "50th Percentile"
    }
   ]
  },
  {
   "title": "Median Event Processing Times by Type",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, avg(irate(midgard_record_event_process_duration_bucket[$__rate_interval])) by (le, type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Request Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg(irate(midgard_api_request_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.90, avg(irate(midgard_api_request_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, avg(irate(midgard_api_request_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "50th Percentile"
    }
   ]
  },
  {
   "title": "Request Counts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(midgard_api_request_duration_count[$__rate_interval])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max 90th Percentile Requests",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, avg(irate(midgard_api_request_duration_bucket[$__rate_interval])) by (le,path))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max 99th Percentile Requests",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg(irate(midgard_api_request_duration_bucket[$__rate_interval])) by (le,path))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}